Repository Talk-Spark/talk-spark-backend, pull requests merged in 2024-12, with the labels that each got.

#25 Feat/#19 게임 시작 및 진행 동기화
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/domain/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/game/config/SocketIOConfig.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/config/WebSocketConfig.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomWebSocketController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/AnswerSubmitRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/GameStartRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/RoomJoinRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/RoomViewController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/UserViewController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/initializer/SparkUserInitializer.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomParticipateRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardQuestion.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/UserCardQuestions.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomListResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/TestUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/repository/SparkUserRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/.gitkeep
  src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
Labels: ✨ Feat, 민우

#31 Refactor/#29 명함 보관함 swagger UI 로 문서화 및 코드 리팩토링
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/domain/card/CardControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/controller/CardController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/entity/Card.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/entity/CardThema.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/CardHolderListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/IndCardHolderCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/StoredCardDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/TeamCardHolderCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/StoredCard.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/repository/StoredCardRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/config/SocketIOConfig.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/dto/SparkUserDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/SwaggerConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/dto/ResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
  src/main/java/mutsa/yewon/talksparkbe/global/util/SecurityUtil.java
  src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java
Labels: ♻️ Refactor

#34 Refactor/#30 방명록 보관함 swagger 리팩토링
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookContent.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookPostRequestDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: ♻️ Refactor

#33 refactor: #32 프론트 요구사항에 맞춰 리팩토링
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java
Labels: ♻️ Refactor, 민우

#38 Chore: #30 CardControllerTest 주석처리
  src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java
Labels: 💡 Comment

#40 Resolve merge conflict
  src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java
Labels: 💡 Comment

#41 Chore: 주석 변경
  src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java
Labels: 💡 Comment

#44 refactor: #43 프론트 요구사항 리팩토링
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardResponseCustomDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
Labels: ♻️ Refactor, 민우

#37 Feat:#36 회원 탈퇴 API추가 및 Swagger UI에 명시 완료
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/SparkUserControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/util/SecurityUtil.java
Labels: ✨ Feat

#47 Refactor:#46 명함 보관함 속 명함 보관 객체에 총 명함 갯수 필드 추가
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/CardHolderDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
Labels: ♻️ Refactor

#48 Refactor/#30 방명록 보관함 swagger 리팩토링
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBook.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookRoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
  src/main/java/mutsa/yewon/talksparkbe/global/scheduler/Scheduler.java
Labels: ♻️ Refactor

#55 Refactor/#53 보관된 명함 조회 시 팀 이름과 즐겨찾기 여부 정보 반환하도록 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/CardHolderListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/StoredCardDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/repository/CardHolderRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/SwaggerConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
Labels: ♻️ Refactor

#60 Feat:#59 메인 페이지 화면에 필요한 보관된 명함 목록 반환 API추가
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/MainPageCardHolderDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
Labels: ✨ Feat

#56 Feat: #54 방명록 초기 데이터 생성 구현
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookRoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: ✨ Feat

#65 Chore: #54 명함 테마 및 익명 명함 테마 추가
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: 🔨 Chore

#96 Chore:#95 회원삭제 버그 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
Labels: 🔨 Chore
