Repository Talk-Spark/talk-spark-backend, pull requests merged in 2024-11, with the labels that each got.

#6 feat: #3 방 생성, 참여 기능 구현
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/TalkSparkBeApplication.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/config/RedissonConfig.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/RoomCreateRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/RoomJoinRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/RoomParticipate.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/initializer/SparkUserInitializer.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomParticipateRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/response/RoomListResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/repository/SparkUserRepository.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
Labels: ✨ Feat, 민우

#7 Feat/#4 카카오 로그인회원가입 구현
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/dto/SparkUserDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUserRole.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/repository/SparkUserRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/CustomTalkSparkException.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorResponseEntity.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/TalkSparkExceptionHandler.java
  src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
  src/main/java/mutsa/yewon/talksparkbe/global/util/JWTUtil.java
  src/test/java/mutsa/yewon/talksparkbe/global/util/JWTUtilTest.java
Labels: ✨ Feat

#10 Refactor: #9 JWT 토큰 생성 키 숨김 및 DTO 변환 static 메서드 추가
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/dto/SparkUserDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
  src/main/java/mutsa/yewon/talksparkbe/global/util/JWTUtil.java
  src/test/java/mutsa/yewon/talksparkbe/global/util/JWTUtilTest.java
Labels: ♻️ Refactor

#13 Feat: #11 방 시작 대기 구현
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/domain/game/config/WebSocketConfig.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomWebSocketController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/HostCheckRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/RoomViewController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/UserViewController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomParticipateRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/response/RoomListResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/response/RoomParticipantResponse.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
  src/main/resources/templates/createRoom.html
  src/main/resources/templates/login.html
  src/main/resources/templates/roomDetail.html
  src/main/resources/templates/roomList.html
Labels: ✨ Feat, 민우

#14 Feat/#12 명함 생성/조회/수정/삭제 API 구현
  src/main/java/mutsa/yewon/talksparkbe/domain/card/controller/CardController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/entity/Card.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/repository/CardRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/dto/SparkUserDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/TalkSparkExceptionHandler.java
  src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
  src/main/java/mutsa/yewon/talksparkbe/global/util/JWTUtil.java
Labels: ✨ Feat, 승범

#16 Feat/#8 방명록 생성 조회 기능 구현
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookContent.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListRequestDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookListResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/GuestBookPostRequestDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/room/GuestBookRoomListResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBook.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomSparkUserRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookRoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/global/dto/ResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
Labels: ✨ Feat, 윤정

#20 Feat/#15 swagger UI 적용
  build.gradle
  src/main/java/mutsa/yewon/talksparkbe/domain/card/CardControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/controller/CardController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/view/UserViewController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/SparkUserControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/SwaggerConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/WebSecurityConfig.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/TalkSparkExceptionHandler.java
  src/main/java/mutsa/yewon/talksparkbe/global/security/JWTCheckFilter.java
  src/main/java/mutsa/yewon/talksparkbe/global/swagger/ApiErrorCode.java
  src/main/java/mutsa/yewon/talksparkbe/global/swagger/ApiErrorCodes.java
  src/main/java/mutsa/yewon/talksparkbe/global/swagger/ErrorResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/global/swagger/ExampleHolder.java
  src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java
Labels: ✨ Feat, 승범

#23 Feat/#22 명함 보관함 명함 별 즐겨찾기 기능 구현
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/CardHolderDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/CardHolderListDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/IndCardHolderCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/StoredCardDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/TeamCardHolderCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/StoredCard.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/StoredStatus.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/repository/CardHolderRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/repository/StoredCardRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
  src/test/java/mutsa/yewon/talksparkbe/domain/card/controller/CardControllerTest.java
Labels: ✨ Feat, 승범
