Repository Talk-Spark/talk-spark-backend, pull requests merged in 2025-03, with the labels that each got.

#143 [Deploy] 정답 명함 공개 오류 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/card/controller/CardController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameQuestionManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SockectIoRoomHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SocketIoGameHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/global/util/SecurityUtil.java
Labels: bug

#145 Fix/#144 명함 저장 로직 오류 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
Labels: bug

#147 Fix: #130 방번호 에러 해결
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
Labels: bug

#148 Merge the develop branch into the main branch. 
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
Labels: 🧩 Merge

#150 Refactor:#149 메인 화면에 필요한 보관된 명함 dto에 명함보관객체 id 추가
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/MainPageCardHolderDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: bug, ♻️ Refactor

#152 Merge the develop branch into the main branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/controller/CardHolderController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/MainPageCardHolderDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoom.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: 🧩 Merge

#154 Chore:#153 메인 화면에 필요한 보관된 명함 api 문서 데이터 추가
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java
Labels: 🔨 Chore

#155 [Deploy] 메인 화면에 필요한 보관된 명함 데이터 제공 API 문서화
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/CardHolderControllerDocs.java
Labels: 🔨 Chore

#151 Chore: #130 질문 더미 및 즐겨찾기 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/QuestionTip.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SocketIoGameHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookRoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: ♻️ Refactor

#156 Merge the develop branch into the main branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/QuestionTip.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SocketIoGameHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookRoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: 🧩 Merge

#157 Feat: #130 질문팁 더미 추가
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/QuestionTip.java
Labels: ✨ Feat

#158 Merge the develop branch into the main branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/QuestionTip.java
Labels: 🧩 Merge

#159 Chore: #130 동일한 랜덤 질문 가도록 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameQuestionManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SocketIoGameHandler.java
Labels: 🔨 Chore

#162 Refactor/#161 명함 문제 출제 시 더미데이터와 명함 항목 데이터를 합한 보기 후보들에서 보기 선정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/RoomControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/DummyOption.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameStateService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomCreateResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
Labels: ♻️ Refactor

#160 Merge the develop branch into the main branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/RoomControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/DummyOption.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameStateService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomCreateResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameQuestionManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/socketiohandler/SocketIoGameHandler.java
Labels: 🧩 Merge
