Repository Talk-Spark/talk-spark-backend, pull requests merged in 2025-02, with the labels that each got.

#121 Refactor/#99 게임 시작 전 후 리팩토링
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/RoomParticipate.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/RoomState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: ♻️ Refactor

#124 Refactor/#99 게임 시작 전 후 리팩토링
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
Labels: ♻️ Refactor

#126 Chore/#112 게임 관련 버그 수정
  .gitignore
  src/main/java/mutsa/yewon/talksparkbe/domain/card/CardControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameTestController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/SparkUserControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/RefreshTokenService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/test/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/RefreshTokenServiceTest.java
Labels: ♻️ Refactor, 🔨 Chore

#131 [Refactor] 게임 로직 수정
  .gitignore
  src/main/java/mutsa/yewon/talksparkbe/domain/card/CardControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameTestController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/SparkUserControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/controller/SparkUserController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/RefreshTokenService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/SparkUserServiceImpl.java
  src/test/java/mutsa/yewon/talksparkbe/domain/sparkUser/service/RefreshTokenServiceTest.java
Labels: ♻️ Refactor

#133 Refactor/#130 명함보관함 방명록생성 로직 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
Labels: ♻️ Refactor

#134 Merge the develop branch into the main branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/repository/RoomRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
Labels: 🧩 Merge

#135 Refactor: #129 게임 종료 처리 시 각 유저 별 http 요청을 받아 처리하도록 API 구현
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameEndController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameResponseDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/swagger/GameEndControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardResponseCustomDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/global/dto/ResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
Labels: ♻️ Refactor

#136 Refactor: #129 게임 종료 처리를 HTTP 요청 방식으로 변경
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameEndController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/dto/EndGameResponseDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/swagger/GameEndControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardResponseCustomDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/global/dto/ResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
Labels: ♻️ Refactor

#137 Refactor/#130 명함보관함 방명록생성 로직 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/RoomIdResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomSparkUserRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: ♻️ Refactor

#138 Refactor/#132 게임 로직 수정을 통한 가독성 향상
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameEndController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameTestController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/swagger/GameEndControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/AnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/PlayerInfo.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GamePlayerManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameQuestionManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameScoreManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
Labels: ♻️ Refactor

#139 Merge the develop branch into the main branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameEndController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/GameTestController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/swagger/GameEndControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/AnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/PlayerInfo.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GamePlayerManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameQuestionManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameScoreManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameStateManager.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/GuestBookControllerDocs.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/dto/guestBook/RoomIdResponseDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/repository/GuestBookRoomSparkUserRepository.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: 🧩 Merge
