Repository Talk-Spark/talk-spark-backend, pull requests merged in 2025-01, with the labels that each got.

#100 Refactor:#98 게임 문제 출제 로직 수정 및 DTO 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/TeamCardHolderCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardBlanksDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
Labels: ♻️ Refactor

#101 Refactor/#98 게임 관련 로직 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/dto/TeamCardHolderCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardBlanksDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CorrectAnswerDto.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
Labels: ♻️ Refactor

#104 Merge the `develop` branch into the `release-dev` branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/request/EndRequest.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/QuestionTip.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/RoomParticipate.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/controller/GuestBookController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
  src/main/java/mutsa/yewon/talksparkbe/global/exception/ErrorCode.java
Labels: 🧩 Merge

#105 Refactor:#102 회원 탈퇴 로직 오류 수정을 위한 엔티티 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardQuestion.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/UserCardQuestions.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
Labels: ♻️ Refactor

#107 [Refactor] 회원 탈퇴 로직 오류 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/CardQuestion.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/UserCardQuestions.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
Labels: ♻️ Refactor

#109 Chore: #54 다중 스레드 동시성 문제 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: 🔨 Chore

#110 [Refactor] 점수판 계산 중 DB접근 최소화
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/service/GuestBookService.java
Labels: ♻️ Refactor

#114 [Refactor]:#111 회원 삭제 로직 버그 수정을 위한 연관관계 메서드 추가
  .gitignore
  src/main/java/mutsa/yewon/talksparkbe/domain/card/dto/CardCreateDTO.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/entity/Card.java
  src/main/java/mutsa/yewon/talksparkbe/domain/card/service/CardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/entity/CardHolder.java
  src/main/java/mutsa/yewon/talksparkbe/domain/cardHolder/service/StoredCardServiceImpl.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomSocketIOHandler.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/RoomParticipate.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBook.java
  src/main/java/mutsa/yewon/talksparkbe/domain/guestBook/entity/GuestBookRoomSparkUser.java
  src/main/java/mutsa/yewon/talksparkbe/domain/sparkUser/entity/SparkUser.java
Labels: ♻️ Refactor

#113 Chore: #99 참가자 중복 참가 가능하게 수정
  src/main/java/mutsa/yewon/talksparkbe/domain/game/controller/RoomController.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/Room.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
Labels: 🔨 Chore

#117 [Chore]:#112 모든 사람이 오답 제출 시에도 응답 값을 반환하도록 수정
  .github/workflows/deploy-main.yml
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/mutsa/yewon/talksparkbe/domain/game/entity/DummyOption.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameStateService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/GameState.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/QuestionGenerator.java
  src/main/java/mutsa/yewon/talksparkbe/global/config/SwaggerConfig.java
Labels: 🐞 Fix

#119 Chore: #99 RoomState로 중복 검사
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/RoomState.java
Labels: 🔨 Chore

#120 Merge the develop branch into the release-dev branch.
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/GameService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/RoomService.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/dto/httpResponse/RoomParticipantResponse.java
  src/main/java/mutsa/yewon/talksparkbe/domain/game/service/util/RoomState.java
Labels: 🧩 Merge
